[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "*" # Protobuf 的 Rust 实现
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "*"
protoc-bin-vendored = "*"

